### Dodaj skladnik
POST http://localhost:8080/ingredients
Content-Type: application/json

{
  "id": "WIEP",
  "name": "Wieprzowina",
  "type": "MEAT"
}

### get recent pizzas
GET http://localhost:8080/pizzas/recent