spring:
  data:
    mongodb:
#      uri: mongodb+srv://karol:<Pa%24%24word%40123>@cluster0.hdt2i.mongodb.net/pizza
      uri:  mongodb://127.0.0.1:27017/karol:<Pa%24%24word%40123>@cluster0.hdt2i.mongodb.net/admin
      database: admin

  security:
    user:
      name: karol
      password: p@ssword

